### ISSUE TITLE
Compatibility between version 7 and 8 of the provider

### ISSUE THREAD

**Issue by ashraidiam** [iwarapter/terraform-provider-pingaccess#92]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v1.0.8`

### Affected Resource(s)

* pingaccess_access_token_validator

Between version 7 and 8 of the provider, there appears to be change in the way the terraform state is handling resources which have a configuration block.

### Terraform Configuration Files

Copied from the documentation as a plain example

```hcl
resource "pingaccess_access_token_validator" "heredoc" {
  class_name = "com.pingidentity.pa.accesstokenvalidators.JwksEndpoint"
  name       = "demo"
  configuration = <<EOF
  {
    "description": null,
    "path": "/bar",
    "subjectAttributeName": "demo",
    "issuer": null,
    "audience": null
  }
  EOF
}
```

### Debug Output

```hcl
$ terraform plan
╷
│ Error: Unexpected configuration format
│ 
│   with pingaccess_access_token_validator.heredoc,
│   on main.tf line 1, in resource "pingaccess_access_token_validator" "heredoc":
│    1: resource "pingaccess_access_token_validator" "heredoc" {
│ 
│ The provider doesn't know how to upgrade from the current state version. Try an earlier release of the provider.
```

### Expected Behavior

When running a plan, no changes or errors should present

### Actual Behavior

As above

### Steps to Reproduce

```bash
docker run --detach --rm -e PING_IDENTITY_DEVOPS_KEY=$PING_IDENTITY_DEVOPS_KEY -e PING_IDENTITY_DEVOPS_USER=$PING_IDENTITY_DEVOPS_USER -e PING_IDENTITY_ACCEPT_EULA=YES -e IMAGE_VERSION=pingaccess-alpine-az11-6.1.4-211015-d9b5 -e PING_IDENTITY_PASSWORD=Password123 -p 9000:9000 pingidentity/pingaccess:6.1.4-edge

```
Create `main.tf`

```hcl
resource "pingaccess_access_token_validator" "heredoc" {
  class_name = "com.pingidentity.pa.accesstokenvalidators.JwksEndpoint"
  name       = "demo"
  configuration = <<EOF
  {
    "description": null,
    "path": "/bar",
    "subjectAttributeName": "demo",
    "issuer": null,
    "audience": null
  }
  EOF
}
```

Create `provider.tf`
```hcl
terraform {
  required_providers {
    pingaccess = {
      source = "iwarapter/pingaccess"
      version = "0.7.0"
    }
  }
}

provider "pingaccess" {
  username = "Administrator"
  password = "Password123"
  base_url = "https://localhost:9000"
  context  = "/pa-admin-api/v3"
}
```

1. `terraform init && terraform apply`
2. Change `version = "0.7.0"` to `version = "0.8.0"` in `provider.tf`
3. `terraform init --upgrade && terraform plan`

### References

* #0000

**Comment by iwarapter** [comment]
Whilst fixing this I came across https://github.com/hashicorp/terraform-plugin-go/issues/115 - once a fix for this is out I should be able to release this.
