### ISSUE TITLE
Support for virtual resources

### ISSUE THREAD

**Issue by mosersil** [iwarapter/terraform-provider-pingaccess#98]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

PingAccess allows to specify an application resource to be "virtual", which allows to return a static response instead of forwarding the request to some backend. 

### New or Affected Resource(s)

* pingaccess_application_resource

### Potential Terraform Configuration

```hcl
resource "pingaccess_application_resource" "static_resource" {
  
  application_id = pingaccess_application.my_application.id

 /*(...some further configuration...)*/
 
 resource_type = "Virtual"

  resource_type_configuration {
    response_generator {
      class_name = "com.pingidentity.pa.resources.responsegenerator.TemplateResponseGenerator"
      configuration = <<EOF
        {
          "template": "<h1>Hello World</h1>",
          "responseCode": 200,
          "mediaType": "text/html;charset=utf8"
        }
      EOF
    }
  }

```

### References

* https://github.com/iwarapter/terraform-provider-pingaccess/pull/97))

**Comment by iwarapter** [comment]
Fixed in https://github.com/iwarapter/terraform-provider-pingaccess/releases/tag/v0.9.0
